workspace:
  base: /drone
  path: .

pipeline:
  build:
    image: python:3
    commands:
      - apt-get update
      - apt-get install libopencv-dev python-opencv python-numpy
      - python main.py